<?php

namespace Obatala\Report;

defined('ABSPATH') || exit;

/**
 * Generates a standardized PDF for a textual document produced in a process step.
 */
class StageDocumentPdf {

    private $process;
    private $node;
    private $field;
    private $document;
    private $generated_by;

    public function __construct(\WP_Post $process, array $node, array $field, array $document, \WP_User $generated_by) {
        $this->process = $process;
        $this->node = $node;
        $this->field = $field;
        $this->document = $document;
        $this->generated_by = $generated_by;
    }

    public function generatePdfBinary() {
        if (!class_exists('\Dompdf\Dompdf')) {
            return null;
        }

        $dompdf = new \Dompdf\Dompdf(['isRemoteEnabled' => false]);
        $dompdf->loadHtml($this->buildHtml(), 'UTF-8');
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        return $dompdf->output();
    }

    private function buildHtml() {
        $generated_at = date_i18n(get_option('date_format') . ' ' . get_option('time_format'));
        $stage_name = $this->node['data']['stageName'] ?? $this->node['id'];
        $label = $this->field['config']['label'] ?? $this->field['title'] ?? __('Stage document', 'obatala');
        $document_type = $this->field['config']['documentType'] ?? '';
        $content = $this->document['content'] ?? '';

        $html = '<!doctype html><html><head><meta charset="utf-8"><style>
            @page { margin: 90px 48px 72px 48px; }
            body { font-family: DejaVu Sans, Arial, sans-serif; color: #222; font-size: 11pt; line-height: 1.5; }
            header { position: fixed; top: -64px; left: 0; right: 0; border-bottom: 1px solid #ccc; padding-bottom: 10px; }
            footer { position: fixed; bottom: -48px; left: 0; right: 0; border-top: 1px solid #ccc; padding-top: 8px; font-size: 8pt; color: #666; }
            h1 { font-size: 18pt; margin: 0 0 4px 0; }
            h2 { font-size: 13pt; margin: 24px 0 8px; }
            .meta { font-size: 9pt; color: #555; margin: 2px 0; }
            .content { white-space: pre-wrap; word-break: break-word; margin-top: 18px; }
        </style></head><body>';

        $html .= '<header>';
        $html .= '<h1>' . esc_html__('Obatala - Curatorial Process Management', 'obatala') . '</h1>';
        $html .= '<p class="meta"><strong>' . esc_html__('Document', 'obatala') . ':</strong> ' . esc_html($label) . '</p>';
        if ($document_type) {
            $html .= '<p class="meta"><strong>' . esc_html__('Type', 'obatala') . ':</strong> ' . esc_html($document_type) . '</p>';
        }
        $html .= '</header>';

        $html .= '<footer>';
        $html .= esc_html__('Generated at', 'obatala') . ': ' . esc_html($generated_at);
        $html .= ' | ' . esc_html__('Generated by', 'obatala') . ': ' . esc_html($this->generated_by->display_name);
        $html .= '</footer>';

        $html .= '<h2>' . esc_html($label) . '</h2>';
        $html .= '<p class="meta"><strong>' . esc_html__('Process', 'obatala') . ':</strong> ' . esc_html($this->process->post_title) . '</p>';
        $html .= '<p class="meta"><strong>' . esc_html__('Step', 'obatala') . ':</strong> ' . esc_html($stage_name) . '</p>';
        $html .= '<p class="meta"><strong>' . esc_html__('Print/export date', 'obatala') . ':</strong> ' . esc_html($generated_at) . '</p>';
        $html .= '<div class="content">' . wp_kses_post($content) . '</div>';
        $html .= '</body></html>';

        return $html;
    }
}
