site_name: Obatala
theme:
  name: 'material'
  language: 'pt'
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.prune
    - navigation.sections
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy

plugins:
  - search
  # - mermaid2
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Organização: organizacao.md
  - Guia do Frontend: gutenberg.md
  - Posts Customizados: posts-customizados.md
  - Metadados Dinâmicos: 
    - Conceito: metadados/metadados.md
    - Implementação: metadados/implementacao.md
  - Tutoriais:
      - Guia básico: tutoriais/guia-dev.md
  # - Modelagem: 
  #     - O Processo: modelagem/processos.md
  #     - Classe Processo: modelagem/classes/processo.md
  #     - Classe Etapa: modelagem/classes/etapa.md
  #     - Classe Notificação: modelagem/classes/notificacao.md
  #     - Classe Setor: modelagem/classes/setor.md
  #     - Classe Pessoa: modelagem/classes/pessoa.md
extra_css:
  - stylesheets/extra.css