site_name: Obatala
theme:
  name: 'material'
  language: 'pt'
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.prune
    - navigation.sections
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy

plugins:
  - search
  # - mermaid2
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Interfaces: interfaces.md
  - Modelagem: 
      # - Classes: modelagem/classes.md
      - O Processo: modelagem/processos.md
      - Classe Processo: modelagem/classes/processo.md
      - Classe Etapa: modelagem/classes/etapa.md
      - Classe Notificacao: modelagem/classes/notificacao.md
      - Classe Pessoa: modelagem/classes/pessoa.md