name: Release

on:
  pull_request:
    branches:
      - main
      - development
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Determine version bump
        id: version
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "development" ]]; then
            echo "Bumping patch version"
            new_version=$(npm version patch --no-git-tag-version)
            echo "new_version=${new_version}" >> $GITHUB_ENV
          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            echo "Bumping minor version"
            new_version=$(npm version minor --no-git-tag-version)
            echo "new_version=${new_version}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Update plugin version and commit
        run: |
          VERSION=${{ env.new_version }}
          # Obtém o branch de destino do PR
          TARGET_BRANCH=${{ github.event.pull_request.base.ref }}
          
          # Atualiza a versão no plugin
          node developer/update-plugin-version.js
          
          # Configura o git
          git config --local user.name "Nocs Bot 🤖"
          git config --local user.email "info@nocslab.ifrn.edu.br"
          
          # Garante que estamos no branch correto
          git checkout $TARGET_BRANCH
          
          # Adiciona os arquivos modificados
          git add package.json obatala.php README.md
          
          # Faz o commit
          git commit -m "chore: update plugin version to ${VERSION}"
          
          # Faz o push do commit para o branch de destino do PR
          git push origin $TARGET_BRANCH

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.new_version }}"
          release_name: "${{ env.new_version }}"
          draft: false
          prerelease: false

      - name: Create plugin ZIP
        run: node developer/create-zip.js

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/obatala.zip
          asset_name: obatala.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
