name: Release Creation

on:
  pull_request:
    branches:
      - main
      - development
    types:
      - closed

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: Build dependencies
        run: npm run build

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.VERSION }}"
          release_name: "${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Create plugin ZIP
        run: node developer/create-zip.js

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/obatala.zip
          asset_name: obatala.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: wainting upload
        run: sleep 12

  updatePlugin:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "${{ secrets.ENVS_PLUGIN_UPDATE }}" > .env

      - name: Download obatala.zip
        run: curl -L -o ./developer/obatala.zip https://github.com/Nocs-lab/Obatala/releases/latest/download/obatala.zip   

      - name: Configs Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar o Playwright e o Chromium
        run: |
           pip install playwright
           playwright install chromium
           pip install python-dotenv 

      - name: Run script update
        run: python ./developer/updatePlugin.py
